version: '3.9'

services:
  server:
    build: ./
    command: gradle bootRun
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://habit_builder_postgres:5432/habitbuilder
      SPRING_DATASOURCE_USERNAME: habitbuilderdocker
      SPRING_DATASOURCE_PASSWORD: habitbuilderdocker
  postgresql:
    container_name: habit_builder_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=habitbuilder
      - POSTGRES_USER=habitbuilderdocker
      - POSTGRES_PASSWORD=habitbuilderdocker

